FROM node:latest AS build

ARG VITE_BACKEND_URL=http://172.184.194.109:3001/api

WORKDIR /build

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx AS final

WORKDIR /usr/share/nginx/html

COPY --from=build /build/dist .

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]